completed week-5-assessment
learn-academy-2022-charlie/week-5-assessment-LoneWanderer101 pull request #1
Opened 2022-06-13 15:56 UTC by LoneWanderer101

# Submitting Week 5 Assessment

### ✅ Completed Files
Mark the following as confirmation that the files in this repository are complete.
- [x] JavaScript Coding Challenges
- [x] Ruby Coding Challenges
- [x] Interview Questions

### 📝 Feedback
If you would like specific feedback on a particular problem please leave details here:

2022-06-14 06:40 UTC, SunkissedQueen approved these changes, later dismissed
Jorge, I am requesting a change. Please place the researched answers in your own word. Ensure you are addressing the definition, an example of a project you created involving that tool, and something interesting that you found from the research.

2022-06-14 06:40 UTC, SunkissedQueen commented on code-challenges.test.js
> +describe ("message", () => {
nice test

2022-06-14 06:40 UTC, SunkissedQueen commented on code-challenges.test.js
> +    const message = (string) => {
awesome one-liner return

2022-06-14 06:40 UTC, SunkissedQueen commented on code-challenges.test.js
> +// Create a function called partLetter that takes in an array of words and a single letter and returns all the words that contain that particular letter.
like your pseudocode

2022-06-14 06:40 UTC, SunkissedQueen commented on code-challenges.test.js
> +const partLetter = (arr, LetterA) => {
great

2022-06-14 06:40 UTC, SunkissedQueen commented on code-challenges.test.js
> +describe ("fullHouse", () => {
indentation looks good

2022-06-14 06:40 UTC, SunkissedQueen commented on code-challenges.test.js
> +const fullHouse = (arr) => {
terrific

2022-06-14 06:40 UTC, SunkissedQueen commented on interview-questions.md
> +  A hash in ruby is a collection of key:value pairs. A hash is similar to an array except taht indexing is done via arbitrary keys of an object type and not trough integer index.If you attempt to acc
What is an example that you can describe? Preferably something you have done

2022-06-14 06:40 UTC, SunkissedQueen commented on interview-questions.md
> +  Rails is a model–view–controller (MVC) framework, providing default structures for a database, a web service, and web pages. Rails facilitates the use of web standards such as JSON or XML for data
Some lines look very similar to the following article: https://www.hashlabs.com/services/ruby-on-rails/#:~:text=Rails%20is%20a%20model%E2%80%93view,for%20display%20and%20user%20interfacing

2022-06-14 06:40 UTC, SunkissedQueen commented on ruby-challenges.rb
> +def find_word array, letter
Why was the method created twice?

2022-06-14 06:40 UTC, SunkissedQueen commented on ruby-challenges.rb
> +def sum_array array
Appreciate your sharing multiple ways

2022-06-14 06:40 UTC, SunkissedQueen commented on ruby-challenges.rb
> +    my_bike.brake(25)
Good work

2022-06-14 06:46 UTC, SunkissedQueen requested changes
Jorge, I am requesting a change. Please place the researched answers in your own word. Ensure you are addressing the definition, an example of a project you created involving that tool, and something interesting that you found from the research.

2022-06-16 17:07 UTC, SunkissedQueen approved these changes
Jorge, the interviews are for you and and a great way to practice conveying how you understand the concepts. Don't rob yourself of the opportunity. Next week please make sure that you are addressing everything in your own words--->the definition, an example of a project you created involving that tool, and something interesting that you found from the research. Practice as much as you can.

2022-06-16 18:13 UTC, merged

2022-06-16 21:17 UTC, LoneWanderer101 commented
Thank you charlean